version: '3.8'
services:
    redis:
        image: redislabs/redismod
        ports:
          - "16379:6379"
        volumes:
          - $PWD/data:/data
        command: --dir /data --loadmodule /usr/lib/redis/modules/redistimeseries.so
